### ISSUE TITLE
nav bar isnt working according to normalized css

### ISSUE THREAD

**Issue by donsalvadori** [donsalvadori/Starter_Kit#1]
seems to be producing some extra left margin but I have no idea where the source of this issue is other than seeing it when I inspect the element.

Please indicate how you fixed also.

**Comment by donsalvadori** [comment]
@SunJLal I'm hoping you have time to explain today

**Comment by SunJLal** [comment]
I'll push up this afternoon, but here is what is happening.

The background is being applied to the wrong element. 
```
   .home-wrap header
```
If you remove the conflicting styles from there and apply them to 
```
  .home-wrap header .header-position
```
along with a few tweaks to your margins

```	    position: fixed;
	    top: 0px;
	    padding-top: 30px;
	    left: 0;
	    bottom: 0px;
	    padding-bottom: 30px;
	    width: 135px;
	    display: flex;
	    flex-direction: column;
	    justify-content: space-between;
	    background-color: white;
```

Please note that you will need to remove the margins you had in and replace them with padding.

Padding pushes the outer containing box away from the text. For more detail on that check out the "css box model"

I hope this helps explain what is going on, I will check in tonight with more functioning code to help you get this fixed.
